### ISSUE TITLE
bug: after restarting the engine, the same step gets executed twice, leading to unexpected behavior

### ISSUE THREAD

**Issue by rbtbar** [hatchet-dev/hatchet#552]
After restarting the engine, the same step gets executed twice, leading to unexpected behavior. Below are the steps to reproduce this issue and the observed logs highlighting the problem.

1. Run the engine: In Terminal 1, execute docker compose up.
2. Start the worker script: In Terminal 2, run the worker script.
3. Start the client script: In Terminal 3, run the client script (just call run_workflow).
4. Wait for one minute, then kill the engine with docker compose down.
5. Wait another minute and start the engine again using docker compose up.

Upon restarting the engine, the logs indicate a doubled execution of the same step:

```
2024-06-04T12:33:50.018Z: Step 1
2024-06-04T12:33:50.036Z: Input: {'items': ['c']}
2024-06-04T12:33:50.05Z: Processing 0
2024-06-04T12:33:55.023Z: Processing 1
2024-06-04T12:34:00.025Z: Processing 2
2024-06-04T12:34:05.026Z: Processing 3
2024-06-04T12:34:10.027Z: Processing 4
2024-06-04T12:34:15.027Z: Processing 5
2024-06-04T12:34:20.029Z: Processing 6
2024-06-04T12:34:25.032Z: Processing 7
2024-06-04T12:34:30.033Z: Processing 8
2024-06-04T12:34:35.036Z: Processing 9
2024-06-04T12:34:40.036Z: Processing 10
2024-06-04T12:35:30.05Z: Processing 20
2024-06-04T12:35:34.453Z: Step 1
2024-06-04T12:35:34.464Z: Input: {'items': ['c']}
2024-06-04T12:35:34.471Z: Processing 0
2024-06-04T12:35:35.055Z: Processing 21
2024-06-04T12:35:39.455Z: Processing 1
2024-06-04T12:35:40.058Z: Processing 22
```

The workflow simulates a long running operation:

```
@hatchet.workflow(name="long-workflow")
class LongWorkflow:
    @hatchet.step(name="step1", timeout="1h")
    def step1(self, context):
        context.log("Step 1")
        context.log(f'Input: {context.workflow_input()}')
        for i in range(60):
            context.log(f'Processing {i}')
            context.put_stream(f'Processing item: {i}')
            context.sleep(5)
        context.log('Done sleeping, returning')
        return {"result": "success"}
```

python sdk: hatchet_sdk-0.24.0

Question

Is this behavior intentional, or is it a bug? The expectation is that after restarting, the steps should either continue from where they left off or start over completely, not both.

**Comment by abelanger5** [comment]
Hey @rbtbar, this is not expected behavior. When we lose connection with the worker, we will reassign work after a visibility timeout of 30 seconds. It seems that when the engine is starting up, we are checking the reassignment immediately, which will always be triggered since the workers haven't connected yet. We'll patch a fix to set a delay on checking for reassignments to give the workers a chance to reconnect. 

A few additional questions:
1. We've been planning to have reassignments trigger the retry loop (they currently bypass the retry loop), which means we'll only reassign work if you have set retries greater than 0. Thoughts on the ideal behavior here?
2. Just to be sure, which version of the `hatchet-engine` are you running in docker compose? 

Additionally, the latest version of the Python SDK is `0.26.1` (though this shouldn't impact the behavior here)

**Comment by rbtbar** [comment]
1. If I was setting retries to 0, then my intention would be to not waste resources, so it makes sense to only reassign tasks when there's still a possibility of success.
2. [v0.28.2](https://github.com/hatchet-dev/hatchet/pkgs/container/hatchet%2Fhatchet-engine/218991264?tag=v0.28.2)

Version 0.26.1 exhibits the same behavior.
