### ISSUE TITLE
Can't receive those unprocessed messages produced before my worker start

### ISSUE THREAD

**Issue by jojopdq** [hatchet-dev/hatchet#740]
Just running the example according to the official quick-start,  
1. sent some messages, then start my worker, the worker can't find any messages, the status of these messages in UI are empty.
2. start my worker, then sent some messages, the worker works well.
Did i forget some configuration or other reason?
Thanks

**Comment by abelanger5** [comment]
Hey @jojopdq, if you haven't ever started the worker, then those events will not be processed, because the events are not linked to a workflow yet (which is done via `register_workflow`). If you have started the worker, and then you spin the worker down and send some events, the events will be processed by the worker when the worker starts back up again.
